// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5mTFk-xuJ4s1a4ssbVD2Yt5BBs103XM',
    appId: '1:592980402193:web:585e7d0d094eb4f85811b0',
    messagingSenderId: '592980402193',
    projectId: 'flutter-app-eb5fe',
    authDomain: 'flutter-app-eb5fe.firebaseapp.com',
    storageBucket: 'flutter-app-eb5fe.firebasestorage.app',
    measurementId: 'G-TVPBZEKJ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdI_gzK1nGIgSs4fv0azcUI8mcqkHcFw',
    appId: '1:592980402193:android:55b33455e0fa7e005811b0',
    messagingSenderId: '592980402193',
    projectId: 'flutter-app-eb5fe',
    storageBucket: 'flutter-app-eb5fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TnT8dWdJ6xg3VB8zis68BouR_kIbxQg',
    appId: '1:592980402193:ios:cb106d56713a8eab5811b0',
    messagingSenderId: '592980402193',
    projectId: 'flutter-app-eb5fe',
    storageBucket: 'flutter-app-eb5fe.firebasestorage.app',
    iosBundleId: 'com.example.wheaterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8TnT8dWdJ6xg3VB8zis68BouR_kIbxQg',
    appId: '1:592980402193:ios:cb106d56713a8eab5811b0',
    messagingSenderId: '592980402193',
    projectId: 'flutter-app-eb5fe',
    storageBucket: 'flutter-app-eb5fe.firebasestorage.app',
    iosBundleId: 'com.example.wheaterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5mTFk-xuJ4s1a4ssbVD2Yt5BBs103XM',
    appId: '1:592980402193:web:a7e91995133620085811b0',
    messagingSenderId: '592980402193',
    projectId: 'flutter-app-eb5fe',
    authDomain: 'flutter-app-eb5fe.firebaseapp.com',
    storageBucket: 'flutter-app-eb5fe.firebasestorage.app',
    measurementId: 'G-8VVM1DFY0C',
  );
}
